// Patches the Podfile post_install hook so third-party Pods build with
// noisy Clang warning categories disabled. This drops upstream warning
// noise (~500+ lines on a clean build) without hiding warnings from
// our own application target — `installer.pods_project.targets` only
// covers Pods targets, never our app target (which lives in a separate
// xcodeproj generated by Expo prebuild). See issue #415.

const PATCH_MARKER = "# canshift-silence-pods-warnings";
const PATCH = `
    ${PATCH_MARKER}
    # Silence noisy Clang warning categories that originate exclusively in
    # third-party Pods (RN core, glog, fmt, Folly, etc.). Scoped to
    # installer.pods_project.targets — our app target is in a separate
    # xcodeproj, so warnings from canshift-mobile/src still surface.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION'] = 'NO'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_OBJC_DESIGNATED_INITIALIZERS'] = 'NO'
        config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
    end
`;

const withPodfilePostInstall = require("./withPodfilePostInstall");

module.exports = function withSilencePodsWarnings(config) {
  return withPodfilePostInstall(
    config,
    "withSilencePodsWarnings",
    PATCH_MARKER,
    PATCH,
  );
};
