// Patches the Podfile post_install hook so third-party Pods build with
// noisy Clang warning categories disabled. This drops upstream warning
// noise (~500+ lines on a clean build) without hiding warnings from
// our own application target — `installer.pods_project.targets` only
// covers Pods targets, never our app target (which lives in a separate
// xcodeproj generated by Expo prebuild). See issue #415.
const { withDangerousMod } = require('@expo/config-plugins')
const fs = require('fs')
const path = require('path')

const PATCH_MARKER = '# canshift-silence-pods-warnings'
const PATCH = `
    ${PATCH_MARKER}
    # Silence noisy Clang warning categories that originate exclusively in
    # third-party Pods (RN core, glog, fmt, Folly, etc.). Scoped to
    # installer.pods_project.targets — our app target is in a separate
    # xcodeproj, so warnings from canshift-mobile/src still surface.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION'] = 'NO'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_OBJC_DESIGNATED_INITIALIZERS'] = 'NO'
        config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
    end
`

module.exports = function withSilencePodsWarnings(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile')
      const podfile = fs.readFileSync(podfilePath, 'utf8')

      if (podfile.includes(PATCH_MARKER)) {
        return config
      }

      // Insert the patch just before the final `end` that closes the
      // `post_install do |installer|` block. The block always ends with a
      // line containing `  end` (two-space indent) followed by the outer
      // target's `end`. Match that pair and inject our patch above it.
      const insertionRegex = /\n( {2}end\nend\s*\n?)$/
      if (!insertionRegex.test(podfile)) {
        throw new Error(
          'withSilencePodsWarnings: could not locate post_install closing in Podfile. ' +
            'The plugin needs an update for the current Expo template.'
        )
      }

      const patched = podfile.replace(insertionRegex, `${PATCH}\n$1`)
      fs.writeFileSync(podfilePath, patched)
      return config
    },
  ])
}
